In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import networkx as nx
from sklearn.manifold import SpectralEmbedding
import itertools
# import plotly.graph_objects as go
from typing import Set, Dict, Any, List, Tuple
from scipy import sparse
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from typing import Union, Optional
#import plotly.express as px
import psutil
from sklearn.manifold import TSNE
import inspect

In [ ]:
d_20250529 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250529.export_triples_sbert.csv')
d_20250530 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250530.export_triples_sbert.csv')
d_20250531 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250531.export_triples_sbert.csv')
d_20250601 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250601.export_triples_sbert.csv')
d_20250602 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250602.export_triples_sbert.csv')
d_20250603 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250603.export_triples_sbert.csv')
d_20250604 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250604.export_triples_sbert.csv')
d_20250605 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250605.export_triples_sbert.csv')
CO_x2d = pd.concat([d_20250529, d_20250530, d_20250531,d_20250601,d_20250602,d_20250603,d_20250604,d_20250605],ignore_index=True)

In [ ]:
d_20160608 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160608.export_triples_sbert.csv')
d_20160609 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160609.export_triples_sbert.csv')
d_20160610 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160610.export_triples_sbert.csv')
d_20160611 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160611.export_triples_sbert.csv')
d_20160613 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160613.export_triples_sbert.csv')
d_20160614 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160614.export_triples_sbert.csv')
d_20160612 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160612.export_triples_sbert.csv')
#d_20160616 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160616.export_triples_sbert.csv')
FL_x2d = pd.concat([d_20160608, d_20160609, d_20160610,d_20160611,d_20160612,d_20160613,d_20160614],ignore_index=True)

In [ ]:
d_20171027 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171027.export_triples_sbert.csv')
d_20171028 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171028.export_triples_sbert.csv')
d_20171029 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171029.export_triples_sbert.csv')
d_20171030 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171030.export_triples_sbert.csv')
d_20171031 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171031.export_triples_sbert.csv')
d_20171101 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171101.export_triples_sbert.csv')
d_20171102 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171102.export_triples_sbert.csv')
d_20171103 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171103.export_triples_sbert.csv')
d_20171104 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171104.export_triples_sbert.csv')
NY_x2d = pd.concat([d_20171027, d_20171028, d_20171029,d_20171030,d_20171101,d_20171102,d_20171103,d_20171104],ignore_index=True)

In [ ]:
d_20140521 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140521.export_triples_sbert.csv')
d_20140522 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140522.export_triples_sbert.csv')
d_20140523 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140523.export_triples_sbert.csv')
d_20140524 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140524.export_triples_sbert.csv')
d_20140525 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140525.export_triples_sbert.csv')
d_20140526 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140526.export_triples_sbert.csv')
d_20140527 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140527.export_triples_sbert.csv')
d_20140528 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140528.export_triples_sbert.csv')
CA_x2d = pd.concat([d_20140521,d_20140522,d_20140523,d_20140524,d_20140525,d_20140526,d_20140527,d_20140528],ignore_index=True)

In [3]:
GD_20140521 = pd.read_csv('/data/elugos/goose_2014/goose_20140521.export.CSV')
GD_20140522 = pd.read_csv('/data/elugos/goose_2014/goose_20140522.export.CSV')
GD_20140523 = pd.read_csv('/data/elugos/goose_2014/goose_20140523.export.CSV')
GD_20140524 = pd.read_csv('/data/elugos/goose_2014/goose_20140524.export.CSV')
GD_20140525 = pd.read_csv('/data/elugos/goose_2014/goose_20140525.export.CSV')
GD_20140526 = pd.read_csv('/data/elugos/goose_2014/goose_20140526.export.CSV')
GD_20140527 = pd.read_csv('/data/elugos/goose_2014/goose_20140527.export.CSV')
GD_20140528 = pd.read_csv('/data/elugos/goose_2014/goose_20140528.export.CSV')
CA_GD = pd.concat([GD_20140521,GD_20140522,GD_20140523,GD_20140524,GD_20140525,GD_20140526,GD_20140527,GD_20140528],ignore_index=True)

In [11]:
GD_20171027 = pd.read_csv('/data/elugos/goose_NY/goose_20171027.export.CSV')
GD_20171028 = pd.read_csv('/data/elugos/goose_NY/goose_20171028.export.CSV')
GD_20171029 = pd.read_csv('/data/elugos/goose_NY/goose_20171029.export.CSV')
GD_20171030 = pd.read_csv('/data/elugos/goose_NY/goose_20171030.export.CSV')
GD_20171031 = pd.read_csv('/data/elugos/goose_NY/goose_20171031.export.CSV')
GD_20171101 = pd.read_csv('/data/elugos/goose_NY/goose_20171101.export.CSV')
GD_20171102 = pd.read_csv('/data/elugos/goose_NY/goose_20171102.export.CSV')
GD_20171103 = pd.read_csv('/data/elugos/goose_NY/goose_20171103.export.CSV')
NY_GD = pd.concat([GD_20171028,GD_20171029,GD_20171027,GD_20171030,GD_20171031,GD_20171101,GD_20171102,GD_20171103],ignore_index=True)

In [8]:
GD_20160608 = pd.read_csv('/data/elugos/goose_FL/goose_20160608.export.CSV')
GD_20160609 = pd.read_csv('/data/elugos/goose_FL/goose_20160609.export.CSV')
GD_20160610 = pd.read_csv('/data/elugos/goose_FL/goose_20160610.export.CSV')
GD_20160611 = pd.read_csv('/data/elugos/goose_FL/goose_20160611.export.CSV')
GD_20160612 = pd.read_csv('/data/elugos/goose_FL/goose_20160612.export.CSV')
GD_20160613 = pd.read_csv('/data/elugos/goose_FL/goose_20160613.export.CSV')
GD_20160614 = pd.read_csv('/data/elugos/goose_FL/goose_20160614.export.CSV')
#GD_20160615 = pd.read_csv('/data/elugos/goose_CO/goose_20160608.export.CSV')
FL_GD = pd.concat([GD_20160608,GD_20160609,GD_20160610,GD_20160611,GD_20160612,GD_20160613,GD_20160614,],ignore_index=True)

In [9]:
GD_20250529 = pd.read_csv('/data/elugos/goose_CO/goose_20250529.export.CSV')
GD_20250530 = pd.read_csv('/data/elugos/goose_CO/goose_20250530.export.CSV')
GD_20250531 = pd.read_csv('/data/elugos/goose_CO/goose_20250531.export.CSV')
GD_20250601 = pd.read_csv('/data/elugos/goose_CO/goose_20250601.export.CSV')
GD_20250602 = pd.read_csv('/data/elugos/goose_CO/goose_20250602.export.CSV')
GD_20250603 = pd.read_csv('/data/elugos/goose_CO/goose_20250603.export.CSV')
GD_20250604 = pd.read_csv('/data/elugos/goose_CO/goose_20250604.export.CSV')
GD_20250605 = pd.read_csv('/data/elugos/goose_CO/goose_20250605.export.CSV')
CO_GD = pd.concat([GD_20250529,GD_20250530,GD_20250531,GD_20250601,GD_20250602,GD_20250603,GD_20250604,GD_20250605],ignore_index=True)

In [29]:
GD_20170808 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170809 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170810 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170811 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170812 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170813 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170814 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
GD_20170815 = pd.read_csv('/data/elugos/goose_VA/goose_20170808.export.CSV')
VA_GD = pd.concat([GD_20170809, GD_20170808, GD_20170810,GD_20170811,GD_20170812,GD_20170813,GD_20170814,GD_20170815],ignore_index=True)

In [30]:
GD_all = pd.concat([CO_GD,CA_GD,NY_GD,FL_GD,VA_GD])

In [18]:
GD_all.head()

,GlobalEventID,date,Year,IsRootEvent,EventCode,EventBaseCode,EventRootCode,QuadClass,GoldsteinScale,NumMentions,...,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL,domain,target,title,text,description
0,1246616308,20250529,2025,1,43.0,43,4,1,2.8,4,...,39.0646,-105.327,CO,20250529,https://www.kotaradio.com/2025/05/28/2-face-ch...,www.kotaradio.com,kotaradio,2 face charges after drug arrest,Authorities have made a major drug bust in wes...,Authorities have made a major drug bust in wes...
1,1246619609,20250529,2025,0,43.0,43,4,1,2.8,40,...,39.0646,-105.327,CO,20250529,https://www.postindependent.com/news/colorados...,www.aspentimes.com,aspentimes,"What Republicans’ ‘big, beautiful bill’ could ...","Coloradans, particularly in high-cost mountain...","Coloradans, particularly in high-cost mountain..."
2,1246619644,20250529,2025,0,14.0,14,1,1,0.0,4,...,39.0646,-105.327,CO,20250529,https://www.summitdaily.com/news/breckenridge-...,www.summitdaily.com,summitdaily,Breckenridge officials worry about some of the...,Share on Facebook Share on Twitter Share on Li...,Consistent reports from the local workforce ab...
3,1246619717,20250529,2025,1,141.0,141,14,3,-6.5,32,...,39.0646,-105.327,CO,20250529,https://www.washingtoninformer.com/worldpride-...,www.washingtoninformer.com,washingtoninformer,"WorldPride Brings Celebrations of Culture, Ide...",Amid federal efforts to reverse and eradicate ...,WorldPride in D.C. celebrates LGBTQ+ rights am...
4,1246620045,20250529,2025,0,190.0,190,19,4,-10.0,6,...,39.0646,-105.327,CO,20250529,https://www.yahoo.com/news/trump-pardons-forme...,www.yahoo.com,yahoo,Trump pardons former GOP Rep. Michael Grimm am...,President Trump on Wednesday took a slew of cl...,President Trump on Wednesday took a slew of cl...

In [31]:
def gdelt_db(df):
    new_df = pd.DataFrame({
    "GlobalEventID": df["GlobalEventID"],
    "date": df["date"],           
    "EventCode": df[["EventCode", "EventBaseCode", "EventRootCode"]]
        .astype(str)
        .agg("_".join, axis=1),
    "state": df["ActionGeo_FeatureID"],
    "title" : df["title"]})

    return new_df

In [32]:
global_db = gdelt_db(GD_all)

In [26]:
global_db.head()

,GlobalEventID,date,EventCode,state,title
0,1246616308,20250529,43.0_43_4,CO,2 face charges after drug arrest
1,1246619609,20250529,43.0_43_4,CO,"What Republicans’ ‘big, beautiful bill’ could ..."
2,1246619644,20250529,14.0_14_1,CO,Breckenridge officials worry about some of the...
3,1246619717,20250529,141.0_141_14,CO,"WorldPride Brings Celebrations of Culture, Ide..."
4,1246620045,20250529,190.0_190_19,CO,Trump pardons former GOP Rep. Michael Grimm am...

In [35]:
global_db.to_csv('global_db.csv', index=False)

In [28]:
pwd

'/data/jupyter'