In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import networkx as nx
from sklearn.manifold import SpectralEmbedding
import itertools
# import plotly.graph_objects as go
from typing import Set, Dict, Any, List, Tuple
from scipy import sparse
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from typing import Union, Optional
#import plotly.express as px
import psutil
from sklearn.manifold import TSNE
import inspect
from pathlib import Path
import os

In [39]:
pd.set_option('display.max_colwidth', None)

In [2]:
d_20250529 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250529.export_triples_sbert.csv')
d_20250530 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250530.export_triples_sbert.csv')
d_20250531 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250531.export_triples_sbert.csv')
d_20250601 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250601.export_triples_sbert.csv')
d_20250602 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250602.export_triples_sbert.csv')
d_20250603 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250603.export_triples_sbert.csv')
d_20250604 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250604.export_triples_sbert.csv')
d_20250605 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250605.export_triples_sbert.csv')
d_20250606 = pd.read_csv('/data/elugos/triples_CO_sbert/goose_20250606.export_triples_sbert.csv')

CO_x2d = pd.concat([d_20250529, d_20250530, d_20250531,d_20250601,d_20250602,d_20250603,d_20250604,d_20250605,d_20250606],ignore_index=True)

In [3]:
d_20160608 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160608.export_triples_sbert.csv')
d_20160609 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160609.export_triples_sbert.csv')
d_20160610 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160610.export_triples_sbert.csv')
d_20160611 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160611.export_triples_sbert.csv')
d_20160612 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160612.export_triples_sbert.csv')
d_20160613 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160613.export_triples_sbert.csv')
d_20160614 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160614.export_triples_sbert.csv')
d_20160615 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160615.export_triples_sbert.csv')
d_20160616 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160616.export_triples_sbert.csv')

#d_20160616 = pd.read_csv('/data/elugos/triples_FL_sbert/goose_20160616.export_triples_sbert.csv')
FL_x2d = pd.concat([d_20160608, d_20160609, d_20160610,d_20160611,d_20160612,d_20160613,d_20160614,d_20160615,d_20160616],ignore_index=True)

FileNotFoundError: [Errno 2] No such file or directory: '/data/elugos/triples_FL_sbert/goose_20160615.export_triples_sbert.csv'

In [ ]:
d_20171027 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171027.export_triples_sbert.csv')
d_20171028 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171028.export_triples_sbert.csv')
d_20171029 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171029.export_triples_sbert.csv')
d_20171030 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171030.export_triples_sbert.csv')
d_20171031 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171031.export_triples_sbert.csv')
d_20171101 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171101.export_triples_sbert.csv')
d_20171102 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171102.export_triples_sbert.csv')
d_20171103 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171103.export_triples_sbert.csv')
d_20171104 = pd.read_csv('/data/elugos/triples_NY_sbert/goose_20171104.export_triples_sbert.csv')
NY_x2d = pd.concat([d_20171027, d_20171028, d_20171029,d_20171030,d_20171101,d_20171102,d_20171103,d_20171104],ignore_index=True)

In [ ]:
d_20140521 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140521.export_triples_sbert.csv')
d_20140522 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140522.export_triples_sbert.csv')
d_20140523 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140523.export_triples_sbert.csv')
d_20140524 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140524.export_triples_sbert.csv')
d_20140525 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140525.export_triples_sbert.csv')
d_20140526 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140526.export_triples_sbert.csv')
d_20140527 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140527.export_triples_sbert.csv')
d_20140528 = pd.read_csv('/data/elugos/triples_CA_sbert/goose_20140528.export_triples_sbert.csv')
CA_x2d = pd.concat([d_20140521,d_20140522,d_20140523,d_20140524,d_20140525,d_20140526,d_20140527,d_20140528],ignore_index=True)

In [7]:
# --- Define CSV paths (Regoose_CA processed exports) ---
GD_20140521 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140521.export_goosed.csv'))
GD_20140522 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140522.export_goosed.csv'))
GD_20140523 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140523.export_goosed.csv'))
GD_20140524 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140524.export_goosed.csv'))
GD_20140525 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140525.export_goosed.csv'))
GD_20140526 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140526.export_goosed.csv'))
GD_20140527 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140527.export_goosed.csv'))
GD_20140528 = pd.read_csv(Path('/data/elugos/regoose_CA/processed/20140528.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_CA = pd.concat(
    [
        GD_20140521,
        GD_20140522,
        GD_20140523,
        GD_20140524,
        GD_20140525,
        GD_20140526,
        GD_20140527,
        GD_20140528,
    ],
    ignore_index=True
)

In [20]:
# --- Define CSV paths (Regoose_NY processed exports) ---
GD_20171027 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171027.export_goosed.csv'))
GD_20171028 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171028.export_goosed.csv'))
GD_20171029 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171029.export_goosed.csv'))
GD_20171030 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171030.export_goosed.csv'))
GD_20171031 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171031.export_goosed.csv'))
GD_20171101 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171101.export_goosed.csv'))
GD_20171102 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171102.export_goosed.csv'))
GD_20171103 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171103.export_goosed.csv'))
GD_20171104 = pd.read_csv(Path('/data/elugos/regoose_NY/processed/20171104.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_NY = pd.concat(
    [
        GD_20171027,
        GD_20171028,
        GD_20171029,
        GD_20171030,
        GD_20171031,
        GD_20171101,
        GD_20171102,
        GD_20171103,
        GD_20171104,
    ],
    ignore_index=True
)

In [8]:
# --- Define CSV paths (Regoose_FL processed exports) ---
GD_20160608 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160608.export_goosed.csv'))
GD_20160609 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160609.export_goosed.csv'))
GD_20160610 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160610.export_goosed.csv'))
GD_20160611 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160611.export_goosed.csv'))
GD_20160613 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160613.export_goosed.csv'))
GD_20160614 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160614.export_goosed.csv'))
GD_20160615 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160615.export_goosed.csv'))
GD_20160616 = pd.read_csv(Path('/data/elugos/regoose_FL/processed/20160616.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_FL = pd.concat(
    [
        GD_20160608,
        GD_20160609,
        GD_20160610,
        GD_20160611,
        GD_20160613,
        GD_20160614,
        GD_20160615,
        GD_20160616,
    ],
    ignore_index=True
)

In [9]:
GD_20250529 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250529.export_goosed.csv'))
GD_20250530 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250530.export_goosed.csv'))
GD_20250531 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250531.export_goosed.csv'))
GD_20250601 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250601.export_goosed.csv'))
GD_20250602 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250602.export_goosed.csv'))
GD_20250603 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250603.export_goosed.csv'))
GD_20250604 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250604.export_goosed.csv'))
GD_20250605 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250605.export_goosed.csv'))
GD_20250606 = pd.read_csv(Path('/data/elugos/regoose_CO/processed/20250606.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_CO = pd.concat(
    [
        GD_20250529,
        GD_20250530,
        GD_20250531,
        GD_20250601,
        GD_20250602,
        GD_20250603,
        GD_20250604,
        GD_20250605,
        GD_20250606,
    ],
    ignore_index=True
)

In [10]:
GD_20170808 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170808.export_goosed.csv'))
GD_20170809 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170809.export_goosed.csv'))
GD_20170810 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170810.export_goosed.csv'))
GD_20170811 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170811.export_goosed.csv'))
GD_20170813 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170813.export_goosed.csv'))
GD_20170814 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170814.export_goosed.csv'))
GD_20170815 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170815.export_goosed.csv'))
GD_20170816 = pd.read_csv(Path('/data/elugos/regoose_VA/processed/20170816.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_VA = pd.concat(
    [
        GD_20170808,
        GD_20170809,
        GD_20170810,
        GD_20170811,
        GD_20170813,
        GD_20170814,
        GD_20170815,
        GD_20170816,
    ],
    ignore_index=True
)

In [11]:
#GD_20190828 = pd.read_csv('/data/elugos/regoose_201908/20190828.export.CSV')
GD_20190827 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190827.export_goosed.csv')
GD_20190826 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190826.export_goosed.csv')
GD_20190825 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190825.export_goosed.csv')
GD_20190824 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190824.export_goosed.csv')
GD_20190823 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190823.export_goosed.csv')
GD_20190822 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190822.export_goosed.csv')
GD_20190821 = pd.read_csv('/data/elugos/regoose_201908/processed_201908/20190821.export_goosed.csv')
GD_201908 = pd.concat([GD_20190821, GD_20190822, GD_20190823,GD_20190824,GD_20190825,GD_20190826,GD_20190827],ignore_index=True)

In [12]:
GD_20200527 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200527.export_goosed.csv')
GD_20200526 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200526.export_goosed.csv')
GD_20200525 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200525.export_goosed.csv')
GD_20200524 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200524.export_goosed.csv')
GD_20200523 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200523.export_goosed.csv')
GD_20200522 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200522.export_goosed.csv')
GD_20200528 = pd.read_csv('/data/elugos/regoose_202005/processed_202005/20200528.export_goosed.csv')
GD_202005 = pd.concat([GD_20200527, GD_20200526, GD_20200525,GD_20200524,GD_20200523,GD_20200522,GD_20200528],ignore_index=True)

In [13]:
GD_20240414 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240414.export_goosed.csv')
GD_20240415 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240415.export_goosed.csv')
GD_20240416 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240416.export_goosed.csv')
GD_20240417 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240417.export_goosed.csv')
GD_20240418 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240418.export_goosed.csv')
GD_20240419 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240419.export_goosed.csv')
GD_20240420 = pd.read_csv('/data/elugos/regoose_202404/processed_202404/20240420.export_goosed.csv')
GD_202404 = pd.concat([GD_20240414, GD_20240415, GD_20240416,GD_20240417,GD_20240418,GD_20240419,GD_20240420],ignore_index=True)

In [14]:
GD_20240927 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240927.export_goosed.csv')
GD_20240928 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240928.export_goosed.csv')
GD_20240929 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240929.export_goosed.csv')
GD_20240924 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240924.export_goosed.csv')
GD_20240925 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240925.export_goosed.csv')
GD_20240930 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240930.export_goosed.csv')
GD_20240926 = pd.read_csv('/data/elugos/regoose_202409_FL/processed_202409_FL/20240926.export_goosed.csv')
GD_202409_FL = pd.concat([GD_20240927, GD_20240928, GD_20240929,GD_20240924,GD_20240925,GD_20240930,GD_20240926],ignore_index=True)

In [15]:
# --- Define CSV paths (September 2024 - NC) ---
GD_20240924_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240924.export_goosed.csv'))
GD_20240925_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240925.export_goosed.csv'))
GD_20240926_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240926.export_goosed.csv'))
GD_20240927_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240927.export_goosed.csv'))
GD_20240928_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240928.export_goosed.csv'))
GD_20240929_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240929.export_goosed.csv'))
GD_20240930_NC = pd.read_csv(Path('/data/elugos/regoose_202409_NC/proccess_202409_NC/20240930.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_202409_NC = pd.concat(
    [
        GD_20240924_NC,
        GD_20240925_NC,
        GD_20240926_NC,
        GD_20240927_NC,
        GD_20240928_NC,
        GD_20240929_NC,
        GD_20240930_NC,
    ],
    ignore_index=True
)

In [16]:
GD_20241205 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241205.export_goosed.csv')
GD_20241202 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241202.export_goosed.csv')
GD_20241203 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241203.export_goosed.csv')
GD_20241206 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241206.export_goosed.csv')
GD_20241207 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241207.export_goosed.csv')
GD_20241204 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241204.export_goosed.csv')
GD_20241201 = pd.read_csv('/data/elugos/regoose_202412/processed_202412/20241201.export_goosed.csv')
GD_202412 = pd.concat([GD_20241205, GD_20241202, GD_20241203,GD_20241206,GD_20241207,GD_20241204,GD_20241201],ignore_index=True)

In [18]:
GD_20250104 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250104.export_goosed.csv'))
GD_20250105 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250105.export_goosed.csv'))
GD_20250106 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250106.export_goosed.csv'))
GD_20250107 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250107.export_goosed.csv'))
GD_20250108 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250108.export_goosed.csv'))
GD_20250109 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250109.export_goosed.csv'))
GD_20250110 = pd.read_csv(Path('/data/elugos/regoose_202501/processed_202501/20250110.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_202501 = pd.concat(
    [
        GD_20250105,
        GD_20250106,
        GD_20250107,
        GD_20250108,
        GD_20250109,
        GD_20250110,
    ],
    ignore_index=True
)

In [22]:
GD_20251015 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251015.export_goosed.csv'))
GD_20251016 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251016.export_goosed.csv'))
GD_20251017 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251017.export_goosed.csv'))
GD_20251018 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251018.export_goosed.csv'))
GD_20251019 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251019.export_goosed.csv'))
GD_20251020 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251020.export_goosed.csv'))
GD_20251021 = pd.read_csv(Path('/data/elugos/regoose_202510/processed_202510/20251021.export_goosed.csv'))

# --- Concatenate into a single DataFrame ---
GD_202510 = pd.concat(
    [
        GD_20251015,
        GD_20251016,
        GD_20251017,
        GD_20251018,
        GD_20251019,
        GD_20251020,
        GD_20251021,
    ],
    ignore_index=True
)

In [23]:
GD_all = pd.concat([GD_CO,GD_CA,GD_NY,GD_FL,GD_VA,GD_202510,GD_202501,GD_202412,GD_202409_FL,GD_202409_NC,GD_202404,GD_202005,GD_201908])

In [68]:
list(Path("/data/elugos/regoose_VA/processed").glob("*"))

[PosixPath('/data/elugos/regoose_VA/processed/20170808.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/20170809.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/20170811.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/20170814.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/20170810.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/20170815.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/20170813.export_goosed.csv'),
 PosixPath('/data/elugos/regoose_VA/processed/openie'),
 PosixPath('/data/elugos/regoose_VA/processed/20170816.export_goosed.csv')]

In [24]:
def gdelt_db(df):
    new_df = pd.DataFrame({
    "GlobalEventID": df["GlobalEventID"],
    "date": df["date"],           
    "EventCode": df[["EventCode", "EventBaseCode", "EventRootCode"]]
        .astype(str)
        .agg("_".join, axis=1),
    "state": df["ActionGeo_FeatureID"],
    "title" : df["title"]})

    return new_df

In [30]:
global_db

,GlobalEventID,date,EventCode,state,title
0,1246616308,20250529,43_43_4,CO,2 face charges after drug arrest
1,1246616515,20250529,46_46_4,CO,"Tony Julianelle, Author at HousingWire"
2,1246619609,20250529,43_43_4,CO,"What Republicans’ ‘big, beautiful bill’ could ..."
3,1246619644,20250529,14_14_1,CO,Breckenridge officials worry about some of the...
4,1246619699,20250529,841_84_8,CO,Colorado’s reintroduced wolves tour new counti...
...,...,...,...,...,...
2079,868739273,20190827,90_90_9,CO,Bear sighting prompts 'secure perimeter' at Lo...
2080,868739832,20190827,40_40_4,CO,1 of 2 Polis recall committees spending money ...
2081,868739878,20190827,10_10_1,CO,Two More GOP Reps. Poised to Exit After Duffy
2082,868743781,20190827,46_46_4,CO,Hickenlooper Endorsement Divides Colorado Demo...
2083,868744182,20190827,46_46_4,CO,Hickenlooper Endorsement Divides Colorado Demo...

In [25]:
global_db = gdelt_db(GD_all)

In [47]:
df_shuffled_reproducible = global_db.sample(frac=1, random_state=42)

In [50]:
df_shuffled_reproducible[['GlobalEventID','title']].tail(15)

,GlobalEventID,title
4289,1269061228,Opinion: The government 'shutdown' explained
9692,550379307,SEBASTIAN SHAKESPEARE: Viscountess is stand-out star at Elton show
11031,1170692496,Delta declares emergency as Boeing aircraft lands in Atlanta
7973,1214098652,"Jury gets OK to consider lesser charge in NYC subway chokehold case, dismisses manslaughter charge"
2755,549282849,"Police: N.C. man threatened to kill ex, family with hatchet, bare hands"
2861,1213090056,Trump taunts Biden over pardoning his son; raises case of imprisoned supporters - OrissaPOST
1375,298423852,New America Media
7178,681629741,No Cookies | The Courier Mail
6598,1219747611,Biden Backs Life-Saving Wildfire Efforts in California
8572,1170460556,Could this be the most meaningful Holocaust memorial in New York?
2717,926026401,President Trump says ‘justice will be served’ for death of George Floyd as Romney urges action
1998,1169881540,"Former Southern Baptist pastor, an election denier, leads FRC Action’s ‘election integrity’ effort – Baptist News Global"
860,1247049916,The Crazy and Bloody Truth About the Murderer Trump Pardoned
5716,702264172,Can President Trump Solve the Qatar Crisis?
1666,868376128,"State, local leaders to attend community reception at CNCC"

In [56]:
global_db.query('GlobalEventID == 702758800')

,GlobalEventID,date,EventCode,state,title
9320,702758800,20171031,43_43_4,NY,"Trump Administration to Defend Cuba Embargo at UN, Reversing Obama"

In [73]:
global_db.to_csv('/data/elugos/global_db_111125.csv', index=False)

In [26]:
len(global_db)

122376

In [35]:
df_play_sample = pd.read_csv(Path('/data/elugos/val_data.csv'))

In [36]:
df_play_sample = df_play_sample.drop_duplicates(subset=['GlobalEventID'])

In [37]:
len(df_play_sample)

73784

In [ ]:
df_play_sample[][]

        Unnamed: 0  GlobalEventID      date  source_index  \
0                0      867742368  20190823           118
1                1      867940985  20190824            13
2                2      867160138  20190722            15
3                3      868690897  20190827           190
4                4      867943064  20190824            29
...            ...            ...       ...           ...
217211       38204      702979068  20171101          3338
217212       38205      702132870  20171029          1091
217220       38213      702500022  20171031           392
217221       38214      703005658  20171101          3801
217237       38230      702973172  20171101          3170

                               subject                               relation  \
0                                Trump                              could get
1                                 Head                      visits Boulder at
2                           Visa delay  keeps Wyoming Symphony conductor from
3                                Pluto                               Deserves
4                              Boulder                                Head of
...                                ...                                    ...
217211                         Suspect                                 Blames
217212                      British PM                                    has
217220                          Battle                                  is in
217221            Beverly Hills Police                          Investigating
217237  Guo Wengui ’s business partner                                demands

                             object  \
0                        poll shows
1            University of Colorado
2                           concert
3                         to Planet
4                              NASA
...                             ...
217211                      Schumer
217212     threat to sack harassers
217220                     Colombia
217221  Harvey Weinstein Complaints
217237          US Guo Global Times

                                                            sbert_text  \
0                                           Trump could get poll shows
1                        Head visits Boulder at University of Colorado
2             Visa delay keeps Wyoming Symphony conductor from concert
3                                             Pluto Deserves to Planet
4                                                 Boulder Head of NASA
...                                                                ...
217211                                          Suspect Blames Schumer
217212                         British PM has threat to sack harassers
217220                                           Battle is in Colombia
217221  Beverly Hills Police Investigating Harvey Weinstein Complaints
217237      Guo Wengui ’s business partner demands US Guo Global Times

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              embedding_json  \
0                                         [0.00760254031047225, -0.08619636297225952, 0.04095075652003288, 0.020267166197299957, -0.012208624742925167, 0.0815868079662323, 0.04082026332616806, -0.0788886547088623, -0.013272951357066631, -0.04565045237541199, -0.062187597155570984, 0.02291431464254856, -0.032352183014154434, 0.016740409657359123, 0.010442979633808136, -0.0032867155969142914, 0.14708104729652405, -0.05991215631365776, -0.005198495462536812, 0.05744362622499466, 0.01637224666774273, 0.041742946952581406, -0.0075437286868691444, -0.027481576427817345, 0.037979476153850555, -0.031995054334402084, -0.016734780743718147, 0.001238099648617208, 0.009886765852570534, -0.03871838375926018, 0.11116182059049606, 0.0038893490564078093, -0.04792868718504906, -0.042822450399398804, 0.01346161775290966, -0.09270638972520828, 0.007623055949807167, 0.028425389900803566, 0.013482123613357544, 0.02691677026450634, 0.027986131608486176, -0.07390771061182022, -0.004588620737195015, -0.0013622238766402006, -0.07833537459373474, -0.048516348004341125, -0.026211166754364967, 0.0005754827288910747, 0.06396987289190292, 0.05370398238301277, -0.0799592062830925, 0.020341284573078156, 0.03374805301427841, -0.09953302890062332, 0.04363930597901344, -0.04344029724597931, -0.031521767377853394, 0.029454132542014122, -0.029969708994030952, 0.05004853382706642, -0.03739451617002487, -0.01637750118970871, -0.015368019230663776, -0.029027551412582397, 0.031775571405887604, 0.01960708573460579, -0.09096114337444305, 0.06299600005149841, 0.026406679302453995, -0.015933696180582047, -0.01589847356081009, 0.07744792848825455, -0.011475238017737865, -0.056013453751802444, 0.05997588112950325, 0.0036454766523092985, -0.05746128410100937, -0.027128830552101135, 0.011564112268388271, -0.048254117369651794, -0.03703227639198303, -0.025710463523864746, -0.04702072963118553, -0.029415475204586983, 0.058212392032146454, -0.019154850393533707, -0.017281003296375275, -0.07401466369628906, -0.019536809995770454, -0.0037849009968340397, -0.10429476201534271, 0.013400737196207047, -0.017790164798498154, 0.054341647773981094, -0.06085633486509323, 0.05082310363650322, 0.015397205017507076, -0.04931972920894623, -0.008712541311979294, 0.07790247350931168, -0.011518984101712704, 0.054010339081287384, -0.0588500089943409, 0.0021441387943923473, -0.048830024898052216, -0.03568825125694275, -0.05364534631371498, -0.006757735274732113, 0.0038289143703877926, 0.06884047389030457, -0.013403062708675861, 0.007767125964164734, 0.0494149811565876, -0.010863849893212318, 0.014608810655772686, -0.11534521728754044, 0.04833954572677612, -0.01688355952501297, -0.0418563038110733, 0.030005237087607384, 0.06274119764566422, 0.006042272783815861, -0.02704678475856781, 0.006932340562343597, 0.08157423138618469, -0.030966952443122864, -0.00033052361686713994, -3.661980816918209e-33, 0.03849753364920616, -0.053505659103393555, 0.026511697098612785, 0.06428836286067963, 0.06347866356372833, 0.10716710984706879, -0.02915123663842678, -0.10662224143743515, 0.02381083555519581, -0.050889547914266586, -0.013011153787374496, 0.11686329543590546, -0.013934503309428692, 0.07626976072788239, 0.061409931629896164, 0.03452078625559807, 0.10151008516550064, 0.01702737808227539, -0.10447806864976883, -0.08705355226993561, -0.014483261853456497, 0.023323912173509598, 0.043401069939136505, -0.03943575918674469, 0.07938173413276672, -0.028876038268208504, 0.02435607835650444, 0.028520463034510612, 0.033101845532655716, 0.003936224151402712, -0.06735212355852127, 0.0013396631693467498, -0.012742026709020138, -0.015248700976371765, -0.017943594604730606, 0.00960209034383297, 0.010078627616167068, -0.03382383659482002, -0.017075974494218826, 0.021644344553351402, 0.049024321138858795, 0.03258996084332466, -0.06167633458971977, 0.08799974620342255, -0.03160502761602402, 0.06900518387556076, 0.06797716021537781, 0.07154486328363419, 0.012451862916350365, 0.009275767020881176, 0.05030932277441025, -0.0004903027438558638, -0.05191446468234062, -0.05472416430711746, 0.059453122317790985, -0.02952842228114605, -0.02460690401494503, -0.0803358256816864, 0.03209663927555084, 0.0023839478380978107, -0.07403823733329773, 0.06231535226106644, 0.004243825096637011, 0.021711809560656548, -0.07255599647760391, -0.004899419844150543, 0.024470996111631393, -0.018290406093001366, 0.005860838573426008, 0.06807415932416916, 0.022380944341421127, 0.0011395654873922467, -0.03437085822224617, -0.03287443891167641, -0.059729646891355515, 0.020853038877248764, -0.06645938009023666, -0.018772006034851074, 0.055855099111795425, 0.021978341042995453, 0.08817408978939056, -0.06682466715574265, 0.05485324561595917, -0.05631565675139427, 0.07345801591873169, 0.012286570854485035, 0.05666930601000786, 0.07368382811546326, -0.047541987150907516, -0.023075813427567482, -0.08821295946836472, -0.012250111438333988, 0.027093341574072838, -0.05305635556578636, -0.0991642028093338, 6.738980543569553e-34, -0.1178772822022438, -0.053467996418476105, -0.004152628593146801, -0.01413046009838581, 0.021566854789853096, 0.006782898213714361, 0.013824624009430408, -0.01852259412407875, 0.05513126030564308, 0.056614965200424194, -0.056685175746679306, -0.035233981907367706, 0.12905240058898926, -0.011112211272120476, -0.04220600798726082, -0.027827367186546326, 0.02291657030582428, -0.0552954338490963, -0.05041545629501343, 0.06025394797325134, 0.016015322878956795, 0.03387540951371193, -0.07291923463344574, 0.13191822171211243, -0.04727336764335632, -0.03518574684858322, 0.004058737773448229, -0.015666628256440163, -0.03247065097093582, -0.024469520896673203, -0.0465179942548275, -0.09961668401956558, -0.07013275474309921, 0.06396916508674622, 0.06159223988652229, 0.04038971662521362, 0.06613633036613464, -0.07095156610012054, -0.03872460871934891, 0.0644955113530159, 0.03423912078142166, -0.07738736271858215, 0.017400575801730156, -0.01604645512998104, -0.06453297287225723, 0.016848696395754814, -0.1280762404203415, 0.078165203332901, -0.013551594689488411, -0.0085018090903759, -0.02776729315519333, 0.08632023632526398, 9.39058190851938e-06, 0.06862814724445343, -0.02928963676095009, -0.04526162147521973, -0.04841448739171028, 0.015261370688676834, 0.07109635323286057, 0.10283484309911728, 0.020016172900795937, -0.052632953971624374, 0.03819946199655533, -0.11377185583114624, 0.06640652567148209, -0.05484450235962868, -0.03551763668656349, -0.05113561823964119, 0.05938161164522171, 0.06494484841823578, 0.07115291804075241, -0.02357807382941246, -0.003976690582931042, -0.061146222054958344, 0.06430507451295853, 0.11147022247314453, -0.03643881902098656, 0.12742942571640015, 0.01942013017833233, 0.01804819330573082, -0.008008330129086971, 0.00010675882367650047, -0.0034536407329142094, -0.09747950732707977, 0.1275547593832016, 0.0036629033274948597, 0.05765467509627342, -0.07784498482942581, 0.026340734213590622, -0.02592831663787365, 0.04858897626399994, -0.02354719117283821, -0.01890985108911991, 0.026570720598101616, -0.03616654872894287, -1.493592449719472e-08, -0.01864343322813511, -0.03682133927941322, 0.05592166632413864, -0.005809710826724768, -0.011168200522661209, 0.023138364776968956, -0.05802355334162712, -0.06212078779935837, 0.06888998299837112, 0.0437137708067894, 0.09771225601434708, -0.005184944253414869, -0.07458557933568954, 0.029697095975279808, 0.043389055877923965, -0.05639674514532089, -0.01360472571104765, -0.018876397982239723, 0.018709728494286537, 0.03168822079896927, 0.01894507184624672, 0.02111024223268032, 0.000580436666496098, 0.05337001755833626, 0.012693327851593494, 0.017151188105344772, -0.010289955884218216, 0.031059686094522476, 0.0014370648423209786, 0.07493151724338531, -0.026473816484212875, -0.12466990202665329, -0.06356322765350342, -0.014594648964703083, 0.0007963815005496144, -0.09797922521829605, -0.051559388637542725, 0.05444462224841118, 0.04344654828310013, 0.045372165739536285, 0.038154054433107376, 0.045699574053287506, 0.020114906132221222, 0.01404341496527195, -0.06464699655771255, -0.02757841721177101, 0.012342267669737339, -0.03445149213075638, 0.026545321568846703, -0.023692121729254723, -0.02564433217048645, 0.01978922076523304, 0.04253130033612251, -0.07759396731853485, 0.06894825398921967, 0.06280748546123505, 0.09186799824237823, -0.007767144124954939, -0.06231635808944702, 0.016762832179665565, 0.006953892298042774, 0.00866491999477148, -0.03718620911240578, 0.07854330539703369]