In [1]:
import networkx as nx
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import csv
import ast
import re

In [28]:
pd.reset_option('all')

As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead.

: boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.

/Users/emilylugos/opt/anaconda3/lib/python3.9/site-packages/pandas/_config/config.py:630: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead.
  warnings.warn(d.msg, FutureWarning)
/Users/emilylugos/opt/anaconda3/lib/python3.9/site-packages/pandas/_config/config.py:630: FutureWarning:
: boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.

  warnings.warn(d.msg, FutureWarning)

In [7]:
pd.set_option('expand_frame_repr', True)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [3]:
d_20250529 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250529.export_triples_sbert.csv')
d_20250530 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250530.export_triples_sbert.csv')
d_20250531 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250531.export_triples_sbert.csv')
d_20250601 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250601.export_triples_sbert.csv')
d_20250602 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250602.export_triples_sbert.csv')
d_20250603 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250603.export_triples_sbert.csv')
d_20250604 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250604.export_triples_sbert.csv')
d_20250605 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/data/triples_CO_sbert/goose_20250605.export_triples_sbert.csv')

In [26]:
f_20250529 = d_20250529.loc[d_20250529['source_index'] == 0]
f_20250530 = d_20250530.loc[d_20250530['source_index'] == 0]
f_20250531 = d_20250531.loc[d_20250531['source_index'] == 0]
f_20250601 = d_20250601.loc[d_20250601['source_index'] == 0]
f_20250602 = d_20250602.loc[d_20250602['source_index'] == 0]
f_20250603 = d_20250603.loc[d_20250603['source_index'] == 0]
f_20250604 = d_20250604.loc[d_20250604['source_index'] == 0]
f_20250605 = d_20250605.loc[d_20250605['source_index'] == 0]

In [29]:
f_20250529.head()

,GlobalEventID,date,source_index,subject,relation,object,sbert_text,embedding_json
141,1246616308,20250529,0,Authorities,have made,major drug bust seizing,Authorities have made major drug bust seizing,"[0.024042688310146332, 0.06702735275030136, 0...."
406,1246616308,20250529,0,Ezra Bald Eagle,are now facing,multiple charges,Ezra Bald Eagle are now facing multiple charges,"[-0.04720691591501236, 0.02111075259745121, -0..."
709,1246616308,20250529,0,Mariah Cross,are now facing,charges,Mariah Cross are now facing charges,"[-0.043441291898489, -0.003956354223191738, 0...."
1174,1246616308,20250529,0,UNET drug task force,stopped vehicle On,Tuesday,UNET drug task force stopped vehicle On Tuesday,"[0.006774120032787323, 0.013990397565066814, 0..."
1588,1246616308,20250529,0,distribution,is in,Rapid City,distribution is in Rapid City,"[0.032722536474466324, 0.006604686379432678, -..."

In [1]:

def dedupe_relation_longest_object(df: pd.DataFrame,
                                  subject_col: str = "subject",
                                  relation_col: str = "relation") -> pd.DataFrame:    
 # Make sure object is string, measure length
    df = df.copy()
    df["_len"] = df[relation_col].fillna("").astype(str).str.len()

    # For each subject, keep row with longest object
    idx = df.groupby(subject_col)["_len"].idxmax()

    result = df.loc[idx].drop(columns=["_len"]).reset_index(drop=True)
    return result

NameError: name 'pd' is not defined

In [8]:
r_20250529 = dedupe_subject_longest_object(f_20250529)
r_20250530 = dedupe_subject_longest_object(f_20250530)
r_20250531 = dedupe_subject_longest_object(f_20250531)
r_20250601 = dedupe_subject_longest_object(f_20250601)
r_20250602 = dedupe_subject_longest_object(f_20250602)
r_20250603 = dedupe_subject_longest_object(f_20250603)
r_20250604 = dedupe_subject_longest_object(f_20250604)
r_20250605 = dedupe_subject_longest_object(f_20250605)

In [9]:
# semantic similarity 
# sentence berg
# less then ten
# use graphic structure with triples
# subject nodes
# relation are paths
# object are also nodes
# get a few of them and start graphing
# use sbert to compare semantic similarity
# get the distances and how are we going to condense
# an avg of all the triples from  one doc to the other
# http://sbert.net/ miniLM
# pairwise triple to triple semantic similarty
# next step is agrerating at the text level

In [13]:
r_20250531

,source_index,subject,relation,object,text
0,0,UCLA,is in,News lists,"UCLA in the News lists selected mentions of UCLA in the world’s news media. Some articles may require registration or a subscription. See more UCLA in the News.\n\n“These fires tested the physical and financial limits of our water infrastructure,” said Gregory Pierce, co-director of UCLA’s Luskin Center for Innovation. “We need to think not just about fixing pipes, but about redesigning systems and supporting populations that are more integrated, more equitable, and resilient to the next crisis.”\n\n“The basic premise of the paper is, ‘Can rising rents help explain why you’re losing transit ridership?’ And it seems to be that they can, because they reduce the likelihood that very high transit riders will live near transit stops,” said urban planning professor Michael Manville, lead author of the paper.\n\nSecond phase of Metro subsidy program to kick off in July after delay | LAist\n\nTeams of researchers from UCLA and UC Davis evaluated the results of Phase 1 of the Metro Mobility program, which involved 1,000 participants from South L.A. According to interviews with 31 participants, researchers from UCLA found that the extra help to afford moving around the city resulted in financial relief, overall stress reduction and increased connection with family and friends.\n\n“This is another year that is not going to help the Colorado basin’s long-term water crisis. It’s going to make things worse,” said Daniel Swain, a UCLA climate scientist. “This year will once again be putting more stress on the Colorado system.”\n\n| Medical Xpress Self-employed women may have better heart health | Medical Xpress\n\nThe study is one of the few to use measures obtained from lab tests and body measures, rather than relying on self-reported measures, to explore the relationship between self-employment and heart disease risk factors, said lead author Dr. Kimberly Narain, assistant professor-in-residence of medicine in the division of general internal medicine and health services research at the David Geffen School of Medicine at UCLA. It is also the only study to consider differences across sex and racial/ethnic minority status.\n\nNutritionists reveal how much protein you really need | Good Housekeeping\n\nEssentially, protein is a chain of amino acids that every cell in your body needs to do its job. “Protein is the main building block for our body,” says Zhaoping Li, the director of the Center for Human Nutrition and the chief of the Division of Clinical Nutrition at the David Geffen School of Medicine at UCLA.\n\nIn its December announcement, OpenAI described the restructure as “the next step in our mission.” But Michael Dorff, another signatory to the open letter and a law professor at UCLA who studies public-benefit corporations, explained to me that PBCs aren’t necessarily an effective way to bring about public good. “They are not great enforcement tools,” he said—they can “nudge” a company toward a given cause but do not give regulators much authority over that commitment."
1,0,world,in,news media,"UCLA in the News lists selected mentions of UCLA in the world’s news media. Some articles may require registration or a subscription. See more UCLA in the News.\n\n“These fires tested the physical and financial limits of our water infrastructure,” said Gregory Pierce, co-director of UCLA’s Luskin Center for Innovation. “We need to think not just about fixing pipes, but about redesigning systems and supporting populations that are more integrated, more equitable, and resilient to the next crisis.”\n\n“The basic premise of the paper is, ‘Can rising rents help explain why you’re losing transit ridership?’ And it seems to be that they can, because they reduce the likelihood that very high transit riders will live near transit stops,” said urban planning professor Michael Manville, lead author of the paper.\n\nSecond phase of Metro subsidy program to kick off in July after delay | LAist\n\nTeams of researchers from UCLA and UC Davis evaluated the results of Phase 1 of the Metro Mobility program, which involved 1,000 participants from South L.A. According to interviews with 31 participants, researchers from UCLA found that the extra help to afford moving around the city resulted in financial relief, overall stress reduction and increased connection with family and friends.\n\n“This is another year that is not going to help the Colorado basin’s long-term water crisis. It’s going to make things worse,” said Daniel Swain, a UCLA climate scientist. “This year will once again be putting more stress on the Colorado system.”\n\n| Medical Xpress Self-employed women may have better heart health | Medical Xpress\n\nThe study is one of the few to use measures obtained from lab tests and body measures, rather than relying on self-reported measures, to explore the relationship between self-employment and heart disease risk factors, said lead author Dr. Kimberly Narain, assistant professor-in-residence of medicine in the division of general internal medicine and health services research at the David Geffen School of Medicine at UCLA. It is also the only study to consider differences across sex and racial/ethnic minority status.\n\nNutritionists reveal how much protein you really need | Good Housekeeping\n\nEssentially, protein is a chain of amino acids that every cell in your body needs to do its job. “Protein is the main building block for our body,” says Zhaoping Li, the director of the Center for Human Nutrition and the chief of the Division of Clinical Nutrition at the David Geffen School of Medicine at UCLA.\n\nIn its December announcement, OpenAI described the restructure as “the next step in our mission.” But Michael Dorff, another signatory to the open letter and a law professor at UCLA who studies public-benefit corporations, explained to me that PBCs aren’t necessarily an effective way to bring about public good. “They are not great enforcement tools,” he said—they can “nudge” a company toward a given cause but do not give regulators much authority over that commitment."
2,0,articles,may require,registration,"UCLA in the News lists selected mentions of UCLA in the world’s news media. Some articles may require registration or a subscription. See more UCLA in the News.\n\n“These fires tested the physical and financial limits of our water infrastructure,” said Gregory Pierce, co-director of UCLA’s Luskin Center for Innovation. “We need to think not just about fixing pipes, but about redesigning systems and supporting populations that are more integrated, more equitable, and resilient to the next crisis.”\n\n“The basic premise of the paper is, ‘Can rising rents help explain why you’re losing transit ridership?’ And it seems to be that they can, because they reduce the likelihood that very high transit riders will live near transit stops,” said urban planning professor Michael Manville, lead author of the paper.\n\nSecond phase of Metro subsidy program to kick off in July after delay | LAist\n\nTeams of researchers from UCLA and UC Davis evaluated the results of Phase 1 of the Metro Mobility program, which involved 1,000 participants from South L.A. According to interviews with 31 participants, researchers from UCLA found that the extra help to afford moving around the city resulted in financial relief, overall stress reduction and increased connection with family and friends.\n\n“This is another year that is not going to help the Colorado basin’s long-term water crisis. It’s going to make things worse,” said Daniel Swain, a UCLA climate scientist. “This year will once again be putting more stress on the Colorado system.”\n\n| Medical Xpress Self-employed women may have better heart health | Medical Xpress\n\nThe study is one of the few to use measures obtained from lab tests and body measures, rather than relying on self-reported measures, to explore the relationship between self-employment and heart disease risk factors, said lead author Dr. Kimberly Narain, assistant professor-in-residence of medicine in the division of general internal medicine and health services research at the David Geffen School of Medicine at UCLA. It is also the only study to consider differences across sex and racial/ethnic minority status.\n\nNutritionists reveal how much protein you really need | Good Housekeeping\n\nEssentially, protein is a chain of amino acids that every cell in your body needs to do its job. “Protein is the main building block for our body,” says Zhaoping Li, the director of the Center for Human Nutrition and the chief of the Division of Clinical Nutrition at the David Geffen School of Medicine at UCLA.\n\nIn its December announcement, OpenAI described the restructure as “the next step in our mission.” But Michael Dorff, another signatory to the open letter and a law professor at UCLA who studies public-benefit corporations, explained to me that PBCs aren’t necessarily an effective way to bring about public good. “They are not great enforcement tools,” he said—they can “nudge” a company toward a given cause but do not give regulators much authority over that commitment."
3,0,more UCLA,is in,News,"UCLA in the News lists selected mentions of UCLA in the world’s news media. Some articles may require registration or a subscription. See more UCLA in the News.\n\n“These fires tested the physical and financial limits of our water infrastructure,” said Gregory Pierce, co-director of UCLA’s Luskin Center for Innovation. “We need to think not just about fixing pipes, but about redesigning systems and supporting populations that are more integrated, more equitable, and resilient to the next crisis.”\n\n“The basic premise of the paper is, ‘Can rising rents help explain why you’re losing transit ridership?’ And it seems to be that they can, because they reduce the likelihood that very high transit riders will live near transit stops,” said urban planning professor Michael Manville, lead author of the paper.\n\nSecond phase of Metro subsidy program to kick off in July after delay | LAist\n\nTeams of researchers from UCLA and UC Davis evaluated the results of Phase 1 of the Metro Mobility program, which involved 1,000 participants from South L.A. According to interviews with 31 participants, researchers from UCLA found that the extra help to afford moving around the city resulted in financial relief, overall stress reduction and increased connection with family and friends.\n\n“This is another year that is not going to help the Colorado basin’s long-term water crisis. It’s going to make things worse,” said Daniel Swain, a UCLA climate scientist. “This year will once again be putting more stress on the Colorado system.”\n\n| Medical Xpress Self-employed women may have better heart health | Medical Xpress\n\nThe study is one of the few to use measures obtained from lab tests and body measures, rather than relying on self-reported measures, to explore the relationship between self-employment and heart disease risk factors, said lead author Dr. Kimberly Narain, assistant professor-in-residence of medicine in the division of general internal medicine and health services research at the David Geffen School of Medicine at UCLA. It is also the only study to consider differences across sex and racial/ethnic minority status.\n\nNutritionists reveal how much protein you really need | Good Housekeeping\n\nEssentially, protein is a chain of amino acids that every cell in your body needs to do its job. “Protein is the main building block for our body,” says Zhaoping Li, the director of the Center for Human Nutrition and the chief of the Division of Clinical Nutrition at the David Geffen School of Medicine at UCLA.\n\nIn its December announcement, OpenAI described the restructure as “the next step in our mission.” But Michael Dorff, another signatory to the open letter and a law professor at UCLA who studies public-benefit corporations, explained to me that PBCs aren’t necessarily an effective way to bring about public good. “They are not great enforcement tools,” he said—they can “nudge” a company toward a given cause but do not give regulators much authority over that commitment."
4,0,Gregory Pierce,co-director of,UCLA ’s Luskin Center for Innovation,"UCLA in the News lists selected mentions of UCLA in the world’s news media. Some articles may require registration or a subscription. See more UCLA in the News.\n\n“These fires tested the physical and financial limits of our water infrastructure,” said Gregory Pierce, co-director of UCLA’s Luskin Center for Innovation. “We need to think not just about fixing pipes, but about redesigning systems and supporting populations that are more integrated, more equitable, and resilient to the next crisis.”\n\n“The basic premise of the paper is, ‘Can rising rents help explain why you’re losing transit ridership?’ And it seems to be that they can, because they reduce the likelihood that very high transit riders will live near transit stops,” said urban planning professor Michael Manville, lead author of the paper.\n\nSecond phase of Metro subsidy program to kick off in July after delay | LAist\n\nTeams of researchers from UCLA and UC Davis evaluated the results of Phase 1 of the Metro Mobility program, which involved 1,000 participants from South L.A. According to interviews with 31 participants, researchers from UCLA found that the extra help to afford moving around the city resulted in financial relief, overall stress reduction and increased connection with family and friends.\n\n“This is another year that is not going to help the Colorado basin’s long-term water crisis. It’s going to make things worse,” said Daniel Swain, a UCLA climate scientist. “This year will once again be putting more stress on the Colorado system.”\n\n| Medical Xpress Self-employed women may have better heart health | Medical Xpress\n\nThe study is one of the few to use measures obtained from lab tests and body measures, rather than relying on self-reported measures, to explore the relationship between self-employment and heart disease risk factors, said lead author Dr. Kimberly Narain, assistant professor-in-residence of medicine in the division of general internal medicine and health services research at the David Geffen School of Medicine at UCLA. It is also the only study to consider differences across sex and racial/ethnic minority status.\n\nNutritionists reveal how much protein you really need | Good Housekeeping\n\nEssentially, protein is a chain of amino acids that every cell in your body needs to do its job. “Protein is the main building block for our body,” says Zhaoping Li, the director of the Center for Human Nutrition and the chief of the Division of Clinical Nutrition at the David Geffen School of Medicine at UCLA.\n\nIn its December announcement, OpenAI described the restructure as “the next step in our mission.” But Michael Dorff, another signatory to the open letter and a law professor at UCLA who studies public-benefit corporations, explained to me that PBCs aren’t necessarily an effective way to bring about public good. “They are not great enforcement tools,” he said—they can “nudge” a company toward a given cause but do not give regulators much authority over that commitment."
5,0,populations,are,integrated,"UCLA in the News lists selected mentions of UCLA in the world’s news media. Some articles may require registration or a subscription. See more UCLA in the News.\n\n“These fires tested the physical and financial limits of our water infrastructure,” said Gregory Pierce, co-director of UCLA’s Luskin Center for Innovation. “We need to think not just about fixing pipes, but about redesigning systems and supporting populations that are more integrated, more equitable, and resilient to the next crisis.”\n\n“The basic premise of the paper is, ‘Can rising rents help explain why you’re losing transit ridership?’ And it seems to be that they can, because they reduce the likelihood that very high transit riders will live near transit stops,” said urban planning professor Michael Manville, lead author of the paper.\n\nSecond phase of Metro subsidy program to kick off in July after delay | LAist\n\nTeams of researchers from UCLA and UC Davis evaluated the results of Phase 1 of the Metro Mobility program, which involved 1,000 participants from South L.A. According to interviews with 31 participants, researchers from UCLA found that the extra help to afford moving around the city resulted in financial relief, overall stress reduction and increased connection with family and friends.\n\n“This is another year that is not going to help the Colorado basin’s long-term water crisis. It’s going to make things worse,” said Daniel Swain, a UCLA climate scientist. “This year will once again be putting more stress on the Colorado system.”\n\n| Medical Xpress Self-employed women may have better heart health | Medical Xpress\n\nThe study is one of the few to use measures obtained from lab tests and body measures, rather than relying on self-reported measures, to explore the relationship between self-employment and heart disease risk factors, said lead author Dr. Kimberly Narain, assistant professor-in-residence of medicine in the division of general internal medicine and health services research at the David Geffen School of Medicine at UCLA. It is also the only study to consider differences across sex and racial/ethnic minority status.\n\nNutritionists reveal how much protein you really need | Good Housekeeping\n\nEssentially, protein is a chain of amino acids that every cell in your body needs to do its job. “Protein is the main building block for our body,” says Zhaoping Li, the director of the Center for Human Nutrition and the chief of the Division of Clinical Nutrition at the David Geffen School of Medicine at UCLA.\n\nIn its December announcement, OpenAI described the restructure as “the next step in our mission.” But Michael Dorff, another signatory to the open letter and a law professor at UCLA who studies public-benefit corporations, explained to me that PBCs aren’t necessarily an effective way to bring about public good. “They are not great enforcement tools,” he said—they can “nudge” a company toward a given cause but do not give regulators much authority over that commitment."

In [ ]:
#generate triples and put them into a file
#csv