In [1]:
import networkx as nx
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import csv
import ast
import re

In [2]:
pd.set_option('expand_frame_repr', True)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [3]:
d_20250529 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250529.export_triples.csv')
d_20250530 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250530.export_triples.csv')
d_20250531 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250531.export_triples.csv')
d_20250601 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250601.export_triples.csv')
d_20250602 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250602.export_triples.csv')
d_20250603 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250603.export_triples.csv')
d_20250604 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250604.export_triples.csv')
d_20250605 = pd.read_csv('/Users/emilylugos/Desktop/Desktop - Emily’s MacBook Pro/summer_2025/research/HSMS_LUGOS/goose_triples/goose_20250605.export_triples.csv')

In [4]:
f_20250529 = d_20250529[d_20250529['source_index'] == 0]
f_20250530 = d_20250530[d_20250530['source_index'] == 0]
f_20250531 = d_20250531[d_20250531['source_index'] == 0]
f_20250601 = d_20250601[d_20250601['source_index'] == 0]
f_20250602 = d_20250602[d_20250602['source_index'] == 0]
f_20250603 = d_20250603[d_20250603['source_index'] == 0]
f_20250604 = d_20250604[d_20250604['source_index'] == 0]
f_20250605 = d_20250605[d_20250605['source_index'] == 0]

In [5]:
f_20250529

,source_index,subject,relation,object,text
0,0,Authorities,have made,major drug bust seizing,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
1,0,Authorities,have made,drug bust seizing,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
2,0,Authorities,have made,major drug bust in western South Dakota,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
3,0,Authorities,have made,major drug bust in western South Dakota seizing,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
4,0,Authorities,have made,drug bust,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
5,0,Authorities,have made,drug bust in western South Dakota seizing,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
6,0,Authorities,have made,drug bust in western South Dakota,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
7,0,Authorities,have made,major drug bust,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
8,0,major drug bust,is in,western South Dakota,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
9,0,Authorities,have made,major drug bust in South Dakota,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
10,0,Authorities,have made,drug bust in South Dakota seizing,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
11,0,Authorities,have made,major drug bust in South Dakota seizing,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
12,0,Authorities,have made,drug bust in South Dakota,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
13,0,UNET drug task force,found over,three ounces,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
14,0,vehicle,is in,Pennington County,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
15,0,UNET drug task force,stopped vehicle On,Tuesday,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
16,0,UNET drug task force,stopped,vehicle in Pennington County,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
17,0,UNET drug task force,stopped,vehicle,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
18,0,UNET drug task force,found over,three ounces of fentanyl powder,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
19,0,Mariah Cross,are facing,charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
20,0,Ezra Bald Eagle,are facing,multiple charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
21,0,Mariah Cross,are now facing,charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
22,0,Ezra Bald Eagle,are facing,charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
23,0,Ezra Bald Eagle,are now facing,multiple charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
24,0,Mariah Cross,are facing,multiple charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
25,0,Mariah Cross,are now facing,multiple charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
26,0,Ezra Bald Eagle,are now facing,charges,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
27,0,distribution,is in,Rapid City,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
28,0,sheriff,’s,office,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."
29,0,they,’re seeing,more,"Authorities have made a major drug bust in western South Dakota, seizing what’s being called one of the region’s largest hauls of fentanyl powder. On Tuesday, the UNET drug task force stopped a vehicle in Pennington County and found over three ounces of fentanyl powder, 35-hundred fake oxy pills, meth, and marijuana. Ezra Bald Eagle and Mariah Cross of Rapid City are now facing multiple charges. Investigators say the drugs were coming from Colorado and were likely headed for distribution in Rapid City. The sheriff’s office says fentanyl and meth remain top threats, and they’re seeing more of it."

In [6]:

def dedupe_subject_longest_object(df: pd.DataFrame,
                                  subject_col: str = "subject",
                                  object_col: str = "object") -> pd.DataFrame:    
    result = df.drop_duplicates(subset=["subject"]).reset_index(drop=True)

    return result

In [7]:
r_20250529 = dedupe_subject_longest_object(f_20250529)
r_20250530 = dedupe_subject_longest_object(f_20250530)
r_20250531 = dedupe_subject_longest_object(f_20250531)
r_20250601 = dedupe_subject_longest_object(f_20250601)
r_20250602 = dedupe_subject_longest_object(f_20250602)
r_20250603 = dedupe_subject_longest_object(f_20250603)
r_20250604 = dedupe_subject_longest_object(f_20250604)
r_20250605 = dedupe_subject_longest_object(f_20250605)

In [ ]:
# semantic similarity 
# sentence berg
# less then ten
# use graphic structure with triples
# subject nodes
# relation are paths
# object are also nodes
# get a few of them and start graphing
# use sbert to compare semantic similarity
# get the distances and how are we going to condense
# an avg of all the triples from  one doc to the other
# http://sbert.net/ miniLM
# pairwise triple to triple semantic similarty
# next step is agrerating at the text level

In [8]:
r_20250530

    source_index  \
0              0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
13             0
14             0
15             0
16             0
17             0
18             0
19             0
20             0
21             0
22             0
23             0
24             0
25             0
26             0
27             0
28             0
29             0
30             0
31             0
32             0
33             0
34             0
35             0
36             0
37             0
38             0
39             0
40             0
41             0
42             0
43             0
44             0
45             0
46             0
47             0
48             0
49             0
50             0
51             0
52             0
53             0
54             0
55             0
56             0
57             0
58             0
59             0
60             0
61             0
62             0
63             0
64             0
65             0
66             0
67             0
68             0
69             0
70             0
71             0

                                                                           subject  \
0                                                                          concern
1                                                                            Trump
2                                                                         Colorado
3                                                                           uptick
4                                                                     recent spike
5                                                                        statement
6             based immigration advocacy organization Voces Unidas de las Montañas
7                   immigration advocacy organization Voces Unidas de las Montañas
8         nonprofit immigration advocacy organization Voces Unidas de las Montañas
9   based nonprofit immigration advocacy organization Voces Unidas de las Montañas
10                                                                              he
11                                                                          number
12                                                                CEO Alex Sánchez
13                                                                      ICE agents
14                                                                 President Trump
15                                                          Voces Unidas President
16                                                          Rep. Elizabeth Velasco
17                                                                    ICE activity
18                                             Eagle County Sheriff James van Beek
19                                                                        incident
20                                                         Garfield County Sheriff
21                                                    New Castle Police Department
22                                                                        presence
23                                                                        counties
24                                                                              it
25                                                                             ICE
26                                                                 ICE ’s presence
27                                                             potential conflicts
28                                                                 Several sheriff
29                                                                       operation
30                                                                          others
31                                                                          agency
32                                                  coordinated enforcement effort
33                                                    U.S. Immigration Enforcement
34                                                                          nation
35                                                                  Sánchez claims
36                                                                ICE spokesperson
37                                                                        ICE data
38                                                               national ICE data
39                                                                 two week period
40                                                                        policies
41                                                                            they
42                                                                      immigrants
43                                                                      operations
44                                                                              us
45                                                                              It
46                                                                 law enforcement
47                                                           local law enforcement
48                                                                 federal arrests
49                                            sharing personal related information
50                                                                 Senate Bill 276
51                                                            Trump administration
52                                                                         Velasco
53                                                            ICE activity hotline
54                                                                     courthouses
55                                                               civil enforcement
56                                            Garfield County courthouse employees
57                                                                      courthouse
58                                                                          agents
59                                                                    Colorado law
60                                                      immigration court hearings
61                                            attending immigration court hearings
62                                                                          rumors
63                                                                            fear
64                                                                         sheriff
65                                                                            them
66                                                  American Civil Liberties Union
67                                                                Feb. 5 ICE raids
68                                                                    False rumors
69                                                                              we
70                                                                         message
71                                                                              We

                       relation  \
0                 uptick across
1                            of
2                        across
3        has drawn concern from
4                         is in
5                         is in
6    released statement at_time
7    released statement at_time
8    released statement at_time
9    released statement at_time
10                       stated
11              increased since
12                         made
13               been active in
14                         took
15                         made
16                    uptick in
17                        is in
18            confirmed at_time
19                      sparked
20                           ’s
21                    confirmed
22                        is in
23                           be
24                   is typical
25                           of
26                        is in
27                      is with
28                           ’s
29                  was part of
30                have violated
31                           ’s
32                        is in
33                     removing
34                           ’s
35                    office ’s
36                 removal from
37                  revealed In
38                  revealed In
39                        is in
40  passing Laken Riley Act for
41                ’re targeting
42                      is with
43                destabilizing
44                         feel
45                      illegal
46                      work in
47       otherwise assisting in
48                        is in
49                      is with
50                    builds on
51                     reversed
52                   sponsor on
53                formed during
54                        is in
55                        is in
56                         told
57                        is in
58                          are
59                bars ICE from
60                         give
61                         give
62               circulating on
63                        is in
64                           to
65             give information
66                       seeing
67                        is in
68                        cause
69                           is
70                           is
71                       should

                                                       object  \
0                                   Colorado ’s Western Slope
1                                      mass deportation plans
2                                               Western Slope
3                                                   advocates
4                                        enforcement activity
5                                     moment of great concern
6                                                        week
7                                                   Last week
8                                                        week
9                                                   Last week
10               Voces Unidas President CEO Alex Sánchez made
11                                                     May 19
12                                                   it clear
13                                 Colorado ’s mountain towns
14                                                     office
15                                                   it clear
16                                               ICE activity
17                                               Eagle County
18                                                  Last week
19                                         social media train
20                                                     Office
21                                                   presence
22                                                 their area
23                              to alerted of ICE ’s presence
24                                             for to alerted
25                                         presence in county
26                                                     county
27                                            law enforcement
28          departments across Western Slope including Pitkin
29  coordinated enforcement effort in central mountain region
30                             our nation ’s immigration laws
31                                        Denver field office
32                                    central mountain region
33                                            criminal aliens
34                                           immigration laws
35                                                     agency
36                                              United States
37                                                 early 2025
38                                                 early 2025
39                                                   February
40                                                    example
41                                                 immigrants
42                                       outstanding warrants
43                                            our communities
44                                                      safer
45           local law enforcement work in conducting arrests
46                                                    arrests
47                          detention of suspected immigrants
48                                          state courthouses
49                                    exceptions for warrants
50                                                protections
51                                                     policy
52                                                       bill
53                                       Trump administration
54                                                   Garfield
55                                                courthouses
56                                                        CPR
57                                  downtown Glenwood Springs
58                                                    allowed
59    conducting civil enforcement actions inside courthouses
60                                                       name
61                                                 their name
62                                                      media
63                                       mountain communities
64                                                     office
65                                            it is happening
66                        higher number of social media posts
67                                                     Denver
68                                                      panic
69                                            should vigilant
70                                            should vigilant
71                                            should prepared


NameError: name 'r_2025053' is not defined